In [77]:
import numpy as np

x = np.ndarray([1, 2, 3])
x.shape

(1, 2, 3)

In [78]:
def convert_dtype(arr, dtype):
    try:
        arr = np.asarray(arr)
        return arr.astype(dtype)
    except TypeError as e:
        raise TypeError(f"Invalid target data type: {dtype}") from e
    except ValueError as e:
        raise ValueError(f"Can't convert value to {dtype}") from e

In [79]:
#checking errors
lst = ["test", 2, 3]
arr = convert_dtype(lst, float)

ValueError: Can't convert value to <class 'float'>

In [80]:
lst = [1, 2, 3]
arr = convert_dtype(lst, float)

In [81]:
def check_dtype(arr, dtype):
    if not isinstance(arr, np.ndarray):
        raise TypeError("input must be a numpy array")
    dtype = np.dtype(dtype)
    return arr.dtype == dtype

check_dtype(np.ndarray([1, 2, 4]), np.ndarray[object])

ValueError: Could not convert numpy.ndarray[object] to a NumPy dtype (via `.dtype` value <attribute 'dtype' of 'numpy.ndarray' objects>).

In [82]:
mat = np.full((3, 4), 5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [83]:
def init_array(shape, value = 0):
    return np.full(shape, value)

In [84]:
zeros = init_array((3, 4)) 
print(zeros)
ones = init_array((3, 4), 1)
print(ones)
tens = init_array((3, 4), 10)
print(tens)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

In [85]:
def init_weights(n_feature, method = "zeros", seed = None):
    if not isinstance(n_feature, int):
        raise TypeError(f"{n_feature} must be an integer")
    if n_feature <= 0:
        raise TypeError(f"{n_feature} must be greater than zero")
    if method == "zeros":
        return np.zeros(n_feature)
    if method == "random":
        if seed is not None:
            np.random.seed(seed)
        return np.random.rand(n_feature) * 0.01 #0.01 is just a factor to make the random numbers smaller
    raise ValueError(f"unsupported method type {method}")

In [86]:
init_weights(4, "random")

array([0.00083091, 0.00879573, 0.0096337 , 0.00863602])

In [87]:
I = np.identity(3, dtype = "float")

In [88]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
np.random.random((3, 3))

array([[0.78065741, 0.42005472, 0.39662741],
       [0.432779  , 0.54741753, 0.86540917],
       [0.35315635, 0.2922191 , 0.69604727]])

In [90]:
np.random.randint(0, 11, (5, 5))

array([[ 7,  1,  5,  0,  0],
       [ 9,  0,  5,  3,  0],
       [ 8,  1,  9,  8,  6],
       [10,  6,  7,  3,  7],
       [ 9,  5,  3,  0,  3]], dtype=int32)

In [91]:
a = ["osama", "basel", "amira"]
np.random.choice(a, size = (3, 5))

array([['amira', 'basel', 'basel', 'osama', 'amira'],
       ['osama', 'basel', 'basel', 'amira', 'basel'],
       ['osama', 'osama', 'osama', 'basel', 'amira']], dtype='<U5')

In [92]:
#example, consider this as a dataset of pictures or images
#save data into numpy files
mat1 = np.ones((3, 4))
mat2 = np.zeros((3, 4))

#save data to a file
#this compreses the file np.savez
np.savez('file_da.npz', ones_mat = mat1, zeros_mat = mat2)

In [93]:
#reading the file
with np.load('file_da.npz') as file:
    mat1 = file['ones_mat']
    mat2 = file['zeros_mat']

In [94]:
mat2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
m1 = np.array([[1, 2, 3],
               [0, 0, 0]])
m2 = np.array([[4, 5, 6], 
               [1, 1, 1]])

In [96]:
#adds more rows so they must have the same number of features(columns)
new_mat = np.vstack((m1, m2))
new_mat

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [1, 1, 1]])

In [97]:
#adds features(columns) to a matrix, so they must have the same number of rows
new_mat = np.hstack((m1, m2))
new_mat

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [98]:
v = np.array([1, 3, 4, 5, 0])
print(np.all(v >= 1))
print(np.any(v >= 1))

False
True

In [99]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0, 5, 3])
print(np.isclose(v1, v2, atol = 1)) #الفرق بين كل رقم واللي تحتية في الفكتور التاني بواحد
print(np.allclose(v1, v2, atol = 1))

[ True  True False  True False]
False

In [100]:
v = np.array([2, 4, 3, 5, 10])
condition = v >= 4
v[condition] = -1
print(condition)
print(v)
new_arr = np.where(condition, -1, v)
print(new_arr)

[False  True False  True  True]
[ 2 -1  3 -1 -1]
[ 2 -1  3 -1 -1]

In [101]:
v1 = np.array([1, 4, 3])
c = 2
summation = v1 + c
multiplication = v1 * c
print(summation)
print(multiplication)

[3 6 5]
[2 8 6]

In [102]:
[[1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0]]
#sparse matrix

[[1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [103]:
#pip install pandas

In [104]:
import pandas as pd

In [105]:
s = pd.Series([1, 2, 3, 4, 5])
print(type(s))
print(s)
s2 = pd.Series([1, 2, 3, 4, 5], index = ["A", "B", "C", "D", "E"])
print(s2)

<class 'pandas.Series'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
A    1
B    2
C    3
D    4
E    5
dtype: int64

In [106]:
# data = [[1, 444, "abc"],
#         [2, 555, "def"],
#         [3, 666, "ghi"],
#         [4, 777, "xyz"]]

data = {'col1': [1, 2, 3, 4],
        'col2': [444, 555, 666, 777],
        'col3': ['abc', 'def', 'ghi', 'xyz']}

df = pd.DataFrame(data)#, columns = ['col1', 'col2', 'col3'])
print(df)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   777  xyz

In [107]:
data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 777, "xyz"]]

df = pd.DataFrame([[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]])
display(data)
display(df)
cols = ['col1', 'col2', 'col3']
df.columns = cols
display(df)
print(df.columns)
print(df.index)
ind = ['r1', 'r2', 'r3', 'r4']
df.index = ind
display(df)

[[1, 444, 'abc'], [2, 555, 'def'], [3, 666, 'ghi'], [4, 777, 'xyz']]

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

Index(['col1', 'col2', 'col3'], dtype='str')
RangeIndex(start=0, stop=4, step=1)

    col1  col2 col3
r1     1   444  abc
r2     2   555  def
r3     3   666  ghi
r4     4   444  xyz

In [108]:
df.dtypes

col1    int64
col2    int64
col3      str
dtype: object

In [109]:
print(df["col1"].dtype, "\n", df["col2"].dtype, "\n", df["col3"].dtype)

int64
 int64
 str

In [113]:
columns = ['col2']
df[columns] = df[columns].astype('category')

In [114]:
df.dtypes

col1       int64
col2    category
col3         str
dtype: object

In [115]:
#EDA -> exploratory data analysis

print(df.head(2))
print(df.tail(2))

    col1 col2 col3
r1     1  444  abc
r2     2  555  def
    col1 col2 col3
r3     3  666  ghi
r4     4  444  xyz

In [116]:
df.describe(include = 'category')

        col2
count      4
unique     3
top      444
freq       2

In [117]:
print(df['col1'].unique())
print(df['col2'].unique())
print(df['col2'].nunique())
print(df['col1'].max())
print(df['col1'].idxmax())
print(df['col1'].sum())

[1 2 3 4]
[444, 555, 666]
Categories (3, int64): [444, 555, 666]
3
4
r4
10

In [118]:
print(df.info())

<class 'pandas.DataFrame'>
Index: 4 entries, r1 to r4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      category
 2   col3    4 non-null      str
dtypes: category(1), int64(1), str(1)
memory usage: 124.0+ bytes
None

In [123]:
x = df['col2'].value_counts()
print(x, "\n\n", type(x))

col2
444    2
555    1
666    1
Name: count, dtype: int64

 <class 'pandas.Series'>